# Generated by Django 4.2 on 2023-04-17 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sailors_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sailor",
            name="position",
            field=models.ForeignKey(
                default=8,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="sailors_app.position",
            ),
        ),
    ]
