# Generated by Django 4.2 on 2023-04-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sailors_app", "0002_position_tasktype_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "LOW"), ("middle", "MIDDLE"), ("high", "HIGH")],
                max_length=10,
            ),
        ),
    ]
