# Generated by Django 4.2 on 2023-04-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sailors_app", "0002_alter_sailor_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="sailor",
            name="board_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
