# Generated by Django 4.2 on 2023-04-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sailors_app", "0003_sailor_board_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sailor",
            name="board_number",
            field=models.CharField(max_length=255),
        ),
    ]
