# Generated by Django 4.2 on 2023-04-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sailors_app", "0004_alter_sailor_board_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="sailor",
            options={"verbose_name": "sailor", "verbose_name_plural": "sailors"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": [
                    models.Case(
                        models.When(priority="high", then=models.Value(1)),
                        models.When(priority="middle", then=models.Value(2)),
                        default=models.Value(3),
                        output_field=models.CharField(),
                    ),
                    "deadline",
                ]
            },
        ),
        migrations.AlterField(
            model_name="sailor",
            name="board_number",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
