# Generated by Django 4.2 on 2023-04-28 22:28

from django.db import migrations
from django.core.management import call_command


def load_func(apps, schema_editor):
    call_command('loaddata', 'sailors_app_to_load.json')


def to_unload_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("sailors_app", "0005_alter_position_options_alter_sailor_options_and_more"),
        ("sessions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_func, to_unload_func),
    ]
